### PR TITLE
Switch to npm fork for pdf kit fixes

### PR DESCRIPTION
**Pull request by DarkGuardAce**
This is a followup to the previous pull request - it includes the changes necessary to switch to a Scoped NPM package of PDFKit that includes a couple of fixes for the latest version.  These changes are pending review into the main PDFKit branch, so hopefully this Scoped approach will be made obsolete soon.

The 2 fixes included in this Scoped package are:

(1) Fix a corner-case that could cause an effectively infinite loop.
(2) Fix a display issue with \n's that are included in text (ex. "alpha\nbeta\ngamma).

### CODE REVIEW

**Comment by NathanaelA** [comment]
Hi Michael,

   Thanks for the pull requests --  Do you have somewhere where this forked PDFKit version is located on Github?    I didn't see it in your repo's...

**Comment by NathanaelA** [comment]
Sweet, that is great.

**Comment by DarkGuardAce** [comment]
Hello again, Nathanael!

Just checking up on this PR - would you like me to modify it to make it merge-ready?  The PDFKit PRs seem to go awhile before being pulled in and these fixes would be nice to have.  Of course, you may prefer not to use a forked version.

If you are ok with working off of such a fork, would it be preferable to move it to a GitHub path rather than an NPM path like it is now?  I haven't dug into it very deeply yet because it hasn't been necessary so far, but I can certainly do so if that would be a better standard to keep to.

Thank you for your help getting these PRs cleaned up!

**Comment by NathanaelA** [comment]
Actually I have no issues with the changes you did.   I just need to make the time to clone your repo to be in the same name space as the reports -- so that people are more likely to trust it.    If it was pulling from the Kellpro repo or a kellpro namespace people shouldn't have any issues (since kellpro still is listed as part of the copyright).  But people might wonder just who DarkGuardAce is.  :-)     

It is on my todo list; but I'm very swamped right now.  :grinning:

**Comment by DarkGuardAce** [comment]
Haha, very good then.  I figured that one of the PRs getting accepted meant that something needed to be fixed with this one - only partially accurate it sounds like, happily.

It is good to be busy!  I should be able to get a KellPro repo or namespace setup with the fork, then I'll get that added to this PR to save you from having to go through any additional steps.  Thank you!

**Comment by DarkGuardAce** [comment]
At your convenience - how does that approach look?  I added the JS files to the KellPro repo then switched to looking there rather than my personal NPM scope.  I ran a few reports from this code to make sure that the switch worked and verified that the PDFKit fixes are working as well.

The oddity with the fork at this point is that it includes both the Coffee files and the JS files, but keeping the Coffee files has the benefit of keeping us more closely related to the main PDFKit repo, which I like.  Let me know if you see anything that you would like changed, sir!

**Comment by DarkGuardAce** [comment]
This redirection is no longer necessary - the PDFKit changes were merged into the master branch last week.

**Pull request closed without merging**
