### PR TITLE
Upgrade pdf kit version

### PR DESCRIPTION
**Pull request by DarkGuardAce**
This will update FluentReports to use the latest version of PDFKit, it fixes font registration in this new version, and it standardizes the layout of Report.error() parameters.  I made a couple of fixes to the PDFKit engine as well while testing this upgrade, but I don't know when they will be reviewed and (hopefully) merged.  Testing indicates that these fixes are not necessary for the latest version of PDFKit to function though, though they do fix a couple of corner-case issues.

I will follow up with another pull request that will change the PDFKit version to an NPM Scoped package that has the rest of the fixes.  These changes include fixes for a long-running loop and a fix for a \n display issue.

### CODE REVIEW

**Comment by DarkGuardAce** [comment]
Ahh, good point.  Yes, that approach sounds great to me.  I'll look into making that change now.  Thanks!

----

Something else that comes to mind that I probably should have mentioned in the initial message - I added an error code to the message on line 822:

```
Report.error("REPORTAPI: Your footer starts with printing some text, then uses an absolute move of greater than a third of the page. Please move first, then print!", '', '', 33);
```

This is useful for us because we want to be able to differentiate that error in our custom error-handling function.  This approach of having an Object be the final entry would support this just fine, but I realize that you may have a preference as to how this is approached.  I mean, only having 1 error with an error code could seem odd.

**Comment by DarkGuardAce** [comment]
Hi there, Nathanael!

The above commit should fix the logging to work as you described.  I removed the error code as well - that approach didn't sit well with me so I am going to look into some other options.

Please let me know if there is anything that you would like changed with the commit, or added to this message chain.  Thank you!

**Comment by NathanaelA** [comment]
Thanks, looks good!

**Comment by NathanaelA** [comment]
v1.18 has been published to npm.  :grinning:

**Pull request merged**
