### PR TITLE
Fixes a bug where a non-existant `logclient` function would be called.

### PR DESCRIPTION
**Pull request by beaudesigns**
`this._scope.funcs.logclient` was being called, yet it doesn't exist anywhere else in FluentReports.

### CODE REVIEW

**Comment by NathanaelA** [comment]
Thanks Beau, I'll get that logclient inside a if statement.

**Comment by NathanaelA** [comment]
@beaudesigns  = Actually question for you, now that I see the code around this; this is inside the ScopedDataObject which is only used by the K project.  Why does it need to be in a if statement?   When a SDO was declared in K for printing it should always have a valid scope.  Did something internally change inside K that a SDO might not have a scope or that the logclient function is no longer a global function inside the core modules?

**Comment by beaudesigns** [comment]
I'm not sure, we're getting errors on several reports now:

> Cannot read property 'logclient' of null

I'm not sure if the scope just isn't being set up properly, or what's happening. As far as the K project goes, I think we'd prefer to not have the expectation that `logclient` is going to exist.

**Comment by NathanaelA** [comment]
Ok, I have no problem putting it inside an if statement.  I suspect if logclient is throwing an error, you probably have a scope issue somewhere in K, either a valid scope wasn't assigned or the scope has somehow been closed before it finished working on the report.   Btw, If you are getting that error, that means another error was trying to be propagated to you via the logclient already.  :-)   

But I'll get the added shortly...

**Comment by beaudesigns** [comment]
Great! Thank you. I'm comfortable with potentially suppressing errors. It will still do `console.error` on the server side. I'd prefer that the report show to the user, instead of nothing visible happening because an error prevented it from completing.

**Comment by NathanaelA** [comment]
v1.08 has been pushed with these changes...

**Comment by beaudesigns** [comment]
Thank you!

**Pull request closed without merging**
